weight_root: &weight_root /home/zmh/hdd/Custom_Projects/action_recognition/my_action_recogn_dev/weights


POSE:
    trtpose:
        size: 256
        backbone: densenet121
        json: lib/pose_estimation/trtpose/human_pose.json
        is_trt: true
        weight:
            - *weight_root # main weight folder
            - pose_estimation/trtpose # sub dir
            - densenet121_256_trt.pth

TRACKER:
    deepsort:
        # sort config
        max_dist: 0.15
        max_iou_distance: 0.8 # 0.8
        max_age: 70 #70
        n_init: 6
        nn_budget: 100 #100

        # reid config
        reid_net: wideresnet # [wideresnet, siamesenet]
        model_path: /home/zmh/hdd/Custom_Projects/action_recognition/my_action_recogn_dev/weights/tracker/deepsort/wideresnet/run-2/epoch_149-best_acc_90.81225033288948.pth
        # model_path:
        #     - *weight_root
        #     - tracker/deepsort
        #     - wideresnet/run-2/epoch_28-best_acc_50.466045272969374.pth
        # reid preprocess config
        gaussian_mask: False # use gaussian mask or not
        img_size: [256, 128] # H, W
        mean: [0.1736, 0.1613, 0.1606]
        std: [0.1523, 0.1429, 0.1443]
        # original mean, std = [0.485, 0.456, 0.406], [0.229, 0.224, 0.225]


CLASSIFIER:
    ## model
    # model_path: ../weights/classifier/action_classifier.pkl
    # classes: ['stand', 'walk', 'run', 'jump', 'sit', 'squat', 'kick', 'punch', 'wave']
    # window_size: 5

    # custom model
    model_path: ../weights/classifier/trained_classifier_GWpose_DNN.pickle
    classes: ['sit', 'stand', 'walk', 'falling']
    window_size: 8