TRACKER:
    deepsort:
        # sort config
        max_dist: 0.2 #0.15
        max_iou_distance: 0.7 # 0.6
        max_age: 70 #70
        n_init: 6
        nn_budget: 100 #100

        # reid config
        reid_net: siamesenet # [wideresnet, siamesenet, align_reid]
        model_path: /home/zmh/hdd/Custom_Projects/action_recognition/my_action_recogn_dev/weights/tracker/deepsort/siamese_reid_ep141.pth # wideresnet_reid_ep125, siamese_reid_ep141
        gaussian_mask: False
        img_size: [256, 128] # height, width
        # for market1501
        mean: [0.1736, 0.1613, 0.1606]
        std: [0.1523, 0.1429, 0.1443]
        # for imagenet pretrained
        # mean: [0.485, 0.456, 0.406]
        # std: [0.229, 0.224, 0.225]

CLASSIFIER:
    ## model
    # model_path: ../weights/classifier/action_classifier.pkl
    # classes: ['stand', 'walk', 'run', 'jump', 'sit', 'squat', 'kick', 'punch', 'wave']
    # window_size: 5

    # custom model
    model_path: ../weights/classifier/trained_classifier_GWpose_DNN.pickle
    classes: ['sit', 'stand', 'walk', 'falling']
    window_size: 8