DEEPSORT:
  model_path: ../weights/tracker/deepsort/reid.pth
  max_dist: 0.1
  max_iou_distance: 0.8
  max_age: 200 #70
  n_init: 3
  nn_budget: 100 #100

CLASSIFIER:
  model_path: ../weights/classifier/action_classifier.pkl
  classes: ['stand', 'walk', 'run', 'jump', 'sit', 'squat', 'kick', 'punch', 'wave']
  window_size: 5