DATASET:
    name: market # market, mars
    data_path: &data_path /home/zmh/hdd/Custom_Projects/object_tracking/datasets/Market_1501
    workers: 1
    batch_size: 32
    img_size:
        - 256 # height
        - 128 # width
    mean: [0.1736, 0.1613, 0.1606]
    std: [0.1523, 0.1429, 0.1443]

# Market Train = [0.1736, 0.1613, 0.1606], [0.1523, 0.1429, 0.1443]

TRAIN:
    fixed_params:
        gpu: 0 # -1 = 'cpu' (OR) 0, 1 = GPU-ID
        reid_net: &reid_net 'siamesenet' # wideresnet, siamesenet
        pretrained: "" # resume model file path
        total_epoch: 100
        scheduler: 'reduce_lr'
        save_root:
            - *data_path
            - save_checkpoints
            - *reid_net

    tune_params: # hyper parameter tuning
        lr: [0.01, 0.009]
        optim: [SGD, Adam]
        gaussian_mask: [True, False]