weight_folder: &weight_folder /home/zmh/hdd/Custom_Projects/action_recognition/my_action_recogn_dev/weights/pose_estimation/trtpose

TRTPOSE:
    size: 256
    backbone: densenet121
    json: /home/zmh/hdd/Custom_Projects/action_recognition/my_action_recogn_dev/src/lib/pose_estimation/trtpose/human_pose.json
    model_path:
        - *weight_folder
        - densenet121_baseline_att_256x256_B_epoch_160_256x256.trt
    min_total_joints: 8
    min_leg_joints: 4
    include_head: True